#!/bin/sh

#
# creates a binary installer of flabc for Win32 with the aid of InnoSetup
#

# temporary target directory for all files
# this is a mirror of the eventual installation directory
TARGETDIR=../flabc.app

# first make sure that binary is compiled with resource forks
cd src; make osxapp; cd ..

# copy data to target
test -d $TARGETDIR || mkdir $TARGETDIR
cp -r flabc.app/* $TARGETDIR/

# documentation and templates
cp README CHANGES LICENSE $TARGETDIR/Contents/Resources/doc/
cp doc/* $TARGETDIR/Contents/Resources/doc/
rm -f $TARGETDIR/Contents/Resources/templates/*
cp templates/* $TARGETDIR/Contents/Resources/templates/
rm -f $TARGETDIR/Contents/Resources/examples/*
cp examples/* $TARGETDIR/Contents/Resources/examples/
