// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "mainwin_msk.h"

void MainWin_msk::cb_window_i(Fl_Double_Window*, void*) {
  // disable Escape shortcut
if (Fl::event()==FL_SHORTCUT && Fl::event_key()==FL_Escape)
  return;
// otherwise call exit callback
cbmenu_file_exit();
}
void MainWin_msk::cb_window(Fl_Double_Window* o, void* v) {
  ((MainWin_msk*)(o->user_data()))->cb_window_i(o,v);
}

void MainWin_msk::cb_New_i(Fl_Menu_*, void*) {
  cbmenu_file_new();
}
void MainWin_msk::cb_New(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_New_i(o,v);
}

void MainWin_msk::cb_menu_file_newwindow_i(Fl_Menu_*, void*) {
  cbmenu_file_newwindow();
}
void MainWin_msk::cb_menu_file_newwindow(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_menu_file_newwindow_i(o,v);
}

void MainWin_msk::cb_New1_i(Fl_Menu_*, void*) {
  cbmenu_file_newtemplate();
}
void MainWin_msk::cb_New1(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_New1_i(o,v);
}

void MainWin_msk::cb_Open_i(Fl_Menu_*, void*) {
  cbmenu_file_open();
}
void MainWin_msk::cb_Open(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Open_i(o,v);
}

void MainWin_msk::cb_Insert_i(Fl_Menu_*, void*) {
  cbmenu_file_insert();
}
void MainWin_msk::cb_Insert(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Insert_i(o,v);
}

void MainWin_msk::cb_Load_i(Fl_Menu_*, void*) {
  cbmenu_file_loadexample();
}
void MainWin_msk::cb_Load(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Load_i(o,v);
}

void MainWin_msk::cb_Save_i(Fl_Menu_*, void*) {
  cbmenu_file_save();
}
void MainWin_msk::cb_Save(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Save_i(o,v);
}

void MainWin_msk::cb_Save1_i(Fl_Menu_*, void*) {
  cbmenu_file_saveas();
}
void MainWin_msk::cb_Save1(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Save1_i(o,v);
}

void MainWin_msk::cb_E_i(Fl_Menu_*, void*) {
  cbmenu_file_exit();
}
void MainWin_msk::cb_E(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_E_i(o,v);
}

void MainWin_msk::cb_Undo_i(Fl_Menu_*, void*) {
  cbmenu_edit_undo();
}
void MainWin_msk::cb_Undo(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Undo_i(o,v);
}

void MainWin_msk::cb_Redo_i(Fl_Menu_*, void*) {
  cbmenu_edit_redo();
}
void MainWin_msk::cb_Redo(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Redo_i(o,v);
}

void MainWin_msk::cb_Mark_i(Fl_Menu_*, void*) {
  textbuffer->select(0,textbuffer->length());
}
void MainWin_msk::cb_Mark(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Mark_i(o,v);
}

void MainWin_msk::cb_Cut_i(Fl_Menu_*, void*) {
  Fl_Text_Editor::kf_cut(0,editor);
}
void MainWin_msk::cb_Cut(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Cut_i(o,v);
}

void MainWin_msk::cb_Copy_i(Fl_Menu_*, void*) {
  Fl_Text_Editor::kf_copy(0,editor);
}
void MainWin_msk::cb_Copy(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Copy_i(o,v);
}

void MainWin_msk::cb_Paste_i(Fl_Menu_*, void*) {
  Fl_Text_Editor::kf_paste(0,editor);
}
void MainWin_msk::cb_Paste(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Paste_i(o,v);
}

void MainWin_msk::cb_menu_edit_cua_linestart_i(Fl_Menu_*, void*) {
  Fl_Text_Editor::kf_home(0,editor);
//int pos = editor->insert_position();
//pos = textbuffer->line_start(pos);
//editor->insert_position(pos);
//editor->show_insert_position();
}
void MainWin_msk::cb_menu_edit_cua_linestart(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_menu_edit_cua_linestart_i(o,v);
}

void MainWin_msk::cb_menu_edit_cua_lineend_i(Fl_Menu_*, void*) {
  Fl_Text_Editor::kf_end(0,editor);
//int pos = editor->insert_position();
//pos = textbuffer->line_end(pos);
//editor->insert_position(pos);
//editor->show_insert_position();
}
void MainWin_msk::cb_menu_edit_cua_lineend(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_menu_edit_cua_lineend_i(o,v);
}

void MainWin_msk::cb_menu_edit_cua_bufferstart_i(Fl_Menu_*, void*) {
  editor->insert_position(0);
editor->show_insert_position();
}
void MainWin_msk::cb_menu_edit_cua_bufferstart(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_menu_edit_cua_bufferstart_i(o,v);
}

void MainWin_msk::cb_menu_edit_cua_bufferend_i(Fl_Menu_*, void*) {
  editor->insert_position(textbuffer->length());
editor->show_insert_position();
}
void MainWin_msk::cb_menu_edit_cua_bufferend(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_menu_edit_cua_bufferend_i(o,v);
}

void MainWin_msk::cb_Goto_i(Fl_Menu_*, void*) {
  int pos = editor->insert_position();
pos = textbuffer->line_start(pos);
editor->insert_position(pos);
editor->show_insert_position();
}
void MainWin_msk::cb_Goto(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Goto_i(o,v);
}

void MainWin_msk::cb_Goto1_i(Fl_Menu_*, void*) {
  int pos = editor->insert_position();
pos = textbuffer->line_end(pos);
editor->insert_position(pos);
editor->show_insert_position();
}
void MainWin_msk::cb_Goto1(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Goto1_i(o,v);
}

void MainWin_msk::cb_Kill_i(Fl_Menu_*, void*) {
  int from, to;
from = editor->insert_position();
to = textbuffer->line_end(from);
if (to == from && to < textbuffer->length()-1)
  to += 1;
textbuffer->remove(from,to);
}
void MainWin_msk::cb_Kill(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Kill_i(o,v);
}

void MainWin_msk::cb_Yank_i(Fl_Menu_*, void*) {
  Fl_Text_Editor::kf_paste(0,editor);
}
void MainWin_msk::cb_Yank(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Yank_i(o,v);
}

void MainWin_msk::cb_Find_i(Fl_Menu_*, void*) {
  cbmenu_search_find();
}
void MainWin_msk::cb_Find(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Find_i(o,v);
}

void MainWin_msk::cb_Find1_i(Fl_Menu_*, void*) {
  cbmenu_search_findagain();
}
void MainWin_msk::cb_Find1(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Find1_i(o,v);
}

void MainWin_msk::cb_Replace_i(Fl_Menu_*, void*) {
  cbmenu_search_replace();
}
void MainWin_msk::cb_Replace(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Replace_i(o,v);
}

void MainWin_msk::cb_Goto2_i(Fl_Menu_*, void*) {
  cbmenu_search_gotoline();
}
void MainWin_msk::cb_Goto2(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Goto2_i(o,v);
}

void MainWin_msk::cb_Goto3_i(Fl_Menu_*, void*) {
  cbmenu_search_gotobar();
}
void MainWin_msk::cb_Goto3(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Goto3_i(o,v);
}

void MainWin_msk::cb_menu_options_larger_i(Fl_Menu_*, void*) {
  cbmenu_options_larger();
}
void MainWin_msk::cb_menu_options_larger(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_menu_options_larger_i(o,v);
}

void MainWin_msk::cb_menu_options_smaller_i(Fl_Menu_*, void*) {
  cbmenu_options_smaller();
}
void MainWin_msk::cb_menu_options_smaller(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_menu_options_smaller_i(o,v);
}

void MainWin_msk::cb_Look_i(Fl_Menu_*, void*) {
  cbmenu_options_look();
}
void MainWin_msk::cb_Look(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Look_i(o,v);
}

void MainWin_msk::cb_Behaviour_i(Fl_Menu_*, void*) {
  cbmenu_options_behaviour();
}
void MainWin_msk::cb_Behaviour(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Behaviour_i(o,v);
}

void MainWin_msk::cb_System_i(Fl_Menu_*, void*) {
  cbmenu_options_system();
}
void MainWin_msk::cb_System(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_System_i(o,v);
}

void MainWin_msk::cb_Save2_i(Fl_Menu_*, void*) {
  cbmenu_options_save();
}
void MainWin_msk::cb_Save2(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Save2_i(o,v);
}

void MainWin_msk::cb_Preview_i(Fl_Menu_*, void*) {
  cbmenu_abc_preview();
}
void MainWin_msk::cb_Preview(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Preview_i(o,v);
}

void MainWin_msk::cb_Preview1_i(Fl_Menu_*, void*) {
  cbmenu_abc_previewtune();
}
void MainWin_msk::cb_Preview1(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Preview1_i(o,v);
}

void MainWin_msk::cb_Listen_i(Fl_Menu_*, void*) {
  cbmenu_abc_listentune();
}
void MainWin_msk::cb_Listen(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Listen_i(o,v);
}

void MainWin_msk::cb_Mark1_i(Fl_Menu_*, void*) {
  cbmenu_abc_marktune();
}
void MainWin_msk::cb_Mark1(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Mark1_i(o,v);
}

void MainWin_msk::cb_Fixup_i(Fl_Menu_*, void*) {
  cbmenu_abc_fixupxrefs();
}
void MainWin_msk::cb_Fixup(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Fixup_i(o,v);
}

void MainWin_msk::cb_Comment_i(Fl_Menu_*, void*) {
  cbmenu_abc_commentregion();
}
void MainWin_msk::cb_Comment(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Comment_i(o,v);
}

void MainWin_msk::cb_Uncomment_i(Fl_Menu_*, void*) {
  cbmenu_abc_uncommentregion();
}
void MainWin_msk::cb_Uncomment(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Uncomment_i(o,v);
}

void MainWin_msk::cb_Octave_i(Fl_Menu_*, void*) {
  cbmenu_abc_regionoctaveup();
}
void MainWin_msk::cb_Octave(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Octave_i(o,v);
}

void MainWin_msk::cb_Octave1_i(Fl_Menu_*, void*) {
  cbmenu_abc_regionoctavedown();
}
void MainWin_msk::cb_Octave1(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Octave1_i(o,v);
}

void MainWin_msk::cb_Insert1_i(Fl_Menu_*, void*) {
  cbmenu_abc_insertheader();
}
void MainWin_msk::cb_Insert1(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Insert1_i(o,v);
}

void MainWin_msk::cb_Pick_i(Fl_Menu_*, void*) {
  cbmenu_abc_midiinstrument();
}
void MainWin_msk::cb_Pick(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Pick_i(o,v);
}

void MainWin_msk::cb_Font_i(Fl_Menu_*, void*) {
  cbmenu_abc_format_font();
}
void MainWin_msk::cb_Font(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Font_i(o,v);
}

void MainWin_msk::cb_Layout_i(Fl_Menu_*, void*) {
  cbmenu_abc_format_layout();
}
void MainWin_msk::cb_Layout(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Layout_i(o,v);
}

void MainWin_msk::cb_Tablature_i(Fl_Menu_*, void*) {
  cbmenu_abc_format_tablature();
}
void MainWin_msk::cb_Tablature(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Tablature_i(o,v);
}

void MainWin_msk::cb_All_i(Fl_Menu_*, void*) {
  cbmenu_abc_format_all();
}
void MainWin_msk::cb_All(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_All_i(o,v);
}

void MainWin_msk::cb_Flabc_i(Fl_Menu_*, void*) {
  cbmenu_help_flabc();
}
void MainWin_msk::cb_Flabc(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Flabc_i(o,v);
}

void MainWin_msk::cb_Flabc1_i(Fl_Menu_*, void*) {
  cbmenu_help_flabcchanges();
}
void MainWin_msk::cb_Flabc1(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Flabc1_i(o,v);
}

void MainWin_msk::cb_Abctab2ps_i(Fl_Menu_*, void*) {
  cbmenu_help_usersguide();
}
void MainWin_msk::cb_Abctab2ps(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Abctab2ps_i(o,v);
}

void MainWin_msk::cb_Abctab2ps1_i(Fl_Menu_*, void*) {
  cbmenu_help_manpage();
}
void MainWin_msk::cb_Abctab2ps1(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_Abctab2ps1_i(o,v);
}

void MainWin_msk::cb_About_i(Fl_Menu_*, void*) {
  cbmenu_help_about();
}
void MainWin_msk::cb_About(Fl_Menu_* o, void* v) {
  ((MainWin_msk*)(o->parent()->user_data()))->cb_About_i(o,v);
}

Fl_Menu_Item MainWin_msk::menu_menubar[] = {
 {"&File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"&New", 0,  (Fl_Callback*)MainWin_msk::cb_New, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"New &Window", 0x4006e,  (Fl_Callback*)MainWin_msk::cb_menu_file_newwindow, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"New from &Template...", 0,  (Fl_Callback*)MainWin_msk::cb_New1, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"&Open...", 0x4006f,  (Fl_Callback*)MainWin_msk::cb_Open, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"&Insert File...", 0,  (Fl_Callback*)MainWin_msk::cb_Insert, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Load Example...", 0,  (Fl_Callback*)MainWin_msk::cb_Load, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"&Save", 0x40073,  (Fl_Callback*)MainWin_msk::cb_Save, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Save &As...", 0,  (Fl_Callback*)MainWin_msk::cb_Save1, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"E&xit", 0x40071,  (Fl_Callback*)MainWin_msk::cb_E, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"&Edit", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"&Undo", 0x4007a,  (Fl_Callback*)MainWin_msk::cb_Undo, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"&Redo", 0,  (Fl_Callback*)MainWin_msk::cb_Redo, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"Mark &All", 0,  (Fl_Callback*)MainWin_msk::cb_Mark, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"CUA Shortcuts", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Cut", 0x40078,  (Fl_Callback*)MainWin_msk::cb_Cut, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Copy", 0x40063,  (Fl_Callback*)MainWin_msk::cb_Copy, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Paste", 0x40076,  (Fl_Callback*)MainWin_msk::cb_Paste, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Goto Line Start", 0xff50,  (Fl_Callback*)MainWin_msk::cb_menu_edit_cua_linestart, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Goto Line End", 0xff57,  (Fl_Callback*)MainWin_msk::cb_menu_edit_cua_lineend, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Goto Buffer Start", 0,  (Fl_Callback*)MainWin_msk::cb_menu_edit_cua_bufferstart, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Goto Buffer End", 0,  (Fl_Callback*)MainWin_msk::cb_menu_edit_cua_bufferend, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Emacs Shortcuts", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Goto Line Start", 0x40061,  (Fl_Callback*)MainWin_msk::cb_Goto, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Goto Line End", 0x40065,  (Fl_Callback*)MainWin_msk::cb_Goto1, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Kill until Line End", 0x4006b,  (Fl_Callback*)MainWin_msk::cb_Kill, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Yank (Paste)", 0x40079,  (Fl_Callback*)MainWin_msk::cb_Yank, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0},
 {"&Search", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"&Find...", 0x40066,  (Fl_Callback*)MainWin_msk::cb_Find, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Find &Again", 0xffc0,  (Fl_Callback*)MainWin_msk::cb_Find1, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"&Replace", 0,  (Fl_Callback*)MainWin_msk::cb_Replace, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"Goto &Line/Column...", 0,  (Fl_Callback*)MainWin_msk::cb_Goto2, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Goto &Bar/Voice/Tune...", 0,  (Fl_Callback*)MainWin_msk::cb_Goto3, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"&Options", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Font Larger", 0x4002b,  (Fl_Callback*)MainWin_msk::cb_menu_options_larger, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Font Smaller", 0x4002d,  (Fl_Callback*)MainWin_msk::cb_menu_options_smaller, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Look and Feel", 0,  (Fl_Callback*)MainWin_msk::cb_Look, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Behaviour", 0,  (Fl_Callback*)MainWin_msk::cb_Behaviour, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"System Environment", 0,  (Fl_Callback*)MainWin_msk::cb_System, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"Save Options", 0,  (Fl_Callback*)MainWin_msk::cb_Save2, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"&Abc", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"&Preview File", 0,  (Fl_Callback*)MainWin_msk::cb_Preview, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Preview &Tune", 0,  (Fl_Callback*)MainWin_msk::cb_Preview1, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"&Listen Tune", 0,  (Fl_Callback*)MainWin_msk::cb_Listen, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"Mark Tune", 0,  (Fl_Callback*)MainWin_msk::cb_Mark1, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Fixup Xrefs", 0,  (Fl_Callback*)MainWin_msk::cb_Fixup, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Comment out", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Comment region", 0,  (Fl_Callback*)MainWin_msk::cb_Comment, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Uncomment region", 0,  (Fl_Callback*)MainWin_msk::cb_Uncomment, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Transpose region", 0,  0, 0, 192, FL_NORMAL_LABEL, 0, 14, 0},
 {"Octave up", 0,  (Fl_Callback*)MainWin_msk::cb_Octave, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Octave down", 0,  (Fl_Callback*)MainWin_msk::cb_Octave1, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Insert Header", 0,  (Fl_Callback*)MainWin_msk::cb_Insert1, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Pick Midi Instrument", 0,  (Fl_Callback*)MainWin_msk::cb_Pick, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"List Format Params", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Font Parameters", 0,  (Fl_Callback*)MainWin_msk::cb_Font, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Layout Parameters", 0,  (Fl_Callback*)MainWin_msk::cb_Layout, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Tablature Parameters", 0,  (Fl_Callback*)MainWin_msk::cb_Tablature, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"All Parameters", 0,  (Fl_Callback*)MainWin_msk::cb_All, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0},
 {"&Help", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Flabc Documentation", 0,  (Fl_Callback*)MainWin_msk::cb_Flabc, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Flabc Changelog", 0,  (Fl_Callback*)MainWin_msk::cb_Flabc1, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Abctab2ps User\'s Guide", 0,  (Fl_Callback*)MainWin_msk::cb_Abctab2ps, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Abctab2ps Manpage", 0,  (Fl_Callback*)MainWin_msk::cb_Abctab2ps1, 0, 128, FL_NORMAL_LABEL, 0, 14, 0},
 {"About flabc", 0,  (Fl_Callback*)MainWin_msk::cb_About, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};
Fl_Menu_Item* MainWin_msk::menu_file_newwindow = MainWin_msk::menu_menubar + 2;
Fl_Menu_Item* MainWin_msk::menu_edit_cua_linestart = MainWin_msk::menu_menubar + 19;
Fl_Menu_Item* MainWin_msk::menu_edit_cua_lineend = MainWin_msk::menu_menubar + 20;
Fl_Menu_Item* MainWin_msk::menu_edit_cua_bufferstart = MainWin_msk::menu_menubar + 21;
Fl_Menu_Item* MainWin_msk::menu_edit_cua_bufferend = MainWin_msk::menu_menubar + 22;
Fl_Menu_Item* MainWin_msk::menu_options_larger = MainWin_msk::menu_menubar + 39;
Fl_Menu_Item* MainWin_msk::menu_options_smaller = MainWin_msk::menu_menubar + 40;

MainWin_msk::MainWin_msk() {
  { window = new Fl_Double_Window(660, 650, "flabc");
    window->callback((Fl_Callback*)cb_window, (void*)(this));
    { menubar = new Fl_Menu_Bar(0, 0, 660, 30);
      menubar->menu(menu_menubar);
    } // Fl_Menu_Bar* menubar
    { tile = new resizable_Fl_Tile(0, 30, 660, 620);
      tile->box(FL_NO_BOX);
      tile->color(FL_BACKGROUND_COLOR);
      tile->selection_color(FL_BACKGROUND_COLOR);
      tile->labeltype(FL_NORMAL_LABEL);
      tile->labelfont(0);
      tile->labelsize(14);
      tile->labelcolor(FL_FOREGROUND_COLOR);
      tile->align(Fl_Align(FL_ALIGN_TOP));
      tile->when(FL_WHEN_RELEASE);
      { grouptop = new Fl_Group(0, 30, 660, 620);
        { editor = new custom_Fl_Text_Editor(0, 30, 660, 600);
          editor->box(FL_DOWN_FRAME);
          editor->color(FL_BACKGROUND2_COLOR);
          editor->selection_color(FL_SELECTION_COLOR);
          editor->labeltype(FL_NORMAL_LABEL);
          editor->labelfont(0);
          editor->labelsize(14);
          editor->labelcolor(FL_FOREGROUND_COLOR);
          editor->align(Fl_Align(FL_ALIGN_TOP));
          editor->when(FL_WHEN_RELEASE);
        } // custom_Fl_Text_Editor* editor
        { infoline = new Fl_Box(0, 630, 660, 20);
          infoline->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
        } // Fl_Box* infoline
        grouptop->end();
        Fl_Group::current()->resizable(grouptop);
      } // Fl_Group* grouptop
      tile->end();
    } // resizable_Fl_Tile* tile
    window->end();
    window->resizable(window);
  } // Fl_Double_Window* window
  textbuffer = new custom_Fl_Text_Buffer();
  editor->buffer(textbuffer);
  window->resizable(grouptop);
  grouptop->resizable(editor);
}

MainWin_msk::~MainWin_msk() {
  delete window;
  delete textbuffer;
}

void MainWin_msk::show() {
  window->show();
}

void MainWin_msk::show(int argc, char**argv) {
  window->show(argc,argv);
}
