// generated by Fast Light User Interface Designer (fluid) version 1.0107

#include "messagebox_msk.h"

void MessageBox_msk::cb_window_i(Fl_Double_Window*, void*) {
  buttonpressed = 3;
window->hide();
}
void MessageBox_msk::cb_window(Fl_Double_Window* o, void* v) {
  ((MessageBox_msk*)(o->user_data()))->cb_window_i(o,v);
}

void MessageBox_msk::cb_button2_i(Fl_Button*, void*) {
  buttonpressed = 2;
}
void MessageBox_msk::cb_button2(Fl_Button* o, void* v) {
  ((MessageBox_msk*)(o->parent()->user_data()))->cb_button2_i(o,v);
}

void MessageBox_msk::cb_button0_i(Fl_Button*, void*) {
  buttonpressed = 0;
}
void MessageBox_msk::cb_button0(Fl_Button* o, void* v) {
  ((MessageBox_msk*)(o->parent()->user_data()))->cb_button0_i(o,v);
}

void MessageBox_msk::cb_button1_i(Fl_Return_Button*, void*) {
  buttonpressed = 1;
}
void MessageBox_msk::cb_button1(Fl_Return_Button* o, void* v) {
  ((MessageBox_msk*)(o->parent()->user_data()))->cb_button1_i(o,v);
}

MessageBox_msk::MessageBox_msk() {
  Fl_Double_Window* w;
  { Fl_Double_Window* o = window = new Fl_Double_Window(427, 128, "flabc");
    w = o;
    o->callback((Fl_Callback*)cb_window, (void*)(this));
    { Fl_Box* o = icon = new Fl_Box(25, 18, 55, 56, "i");
      o->box(FL_THIN_UP_BOX);
      o->color(FL_BACKGROUND2_COLOR);
      o->labelfont(9);
      o->labelsize(34);
      o->labelcolor((Fl_Color)4);
      o->align(FL_ALIGN_CENTER|FL_ALIGN_INSIDE);
    }
    { Fl_Box* o = message = new Fl_Box(110, 18, 290, 47, "message");
      o->align(FL_ALIGN_LEFT|FL_ALIGN_INSIDE);
    }
    { Fl_Button* o = button2 = new Fl_Button(110, 80, 75, 30, "button2");
      o->callback((Fl_Callback*)cb_button2);
    }
    { Fl_Button* o = button0 = new Fl_Button(307, 80, 80, 30, "button0");
      o->shortcut(0xff1b);
      o->callback((Fl_Callback*)cb_button0);
    }
    { Fl_Return_Button* o = button1 = new Fl_Return_Button(206, 80, 80, 30, "button1");
      o->callback((Fl_Callback*)cb_button1);
    }
    o->set_modal();
    o->end();
  }
  buttonpressed = -1;
}

MessageBox_msk::~MessageBox_msk() {
  delete window;
}
