// generated by Fast Light User Interface Designer (fluid) version 1.0107

#ifndef messagebox_msk_h
#define messagebox_msk_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Return_Button.H>

class MessageBox_msk {
public:
  int buttonpressed;
  MessageBox_msk();
  Fl_Double_Window *window;
private:
  void cb_window_i(Fl_Double_Window*, void*);
  static void cb_window(Fl_Double_Window*, void*);
public:
  Fl_Box *icon;
  Fl_Box *message;
  Fl_Button *button2;
private:
  void cb_button2_i(Fl_Button*, void*);
  static void cb_button2(Fl_Button*, void*);
public:
  Fl_Button *button0;
private:
  void cb_button0_i(Fl_Button*, void*);
  static void cb_button0(Fl_Button*, void*);
public:
  Fl_Return_Button *button1;
private:
  void cb_button1_i(Fl_Return_Button*, void*);
  static void cb_button1(Fl_Return_Button*, void*);
public:
  virtual ~MessageBox_msk();
};
#endif
